version: '2.1'

services:
  users-db:
    container_name: users-db
    build: https://github.com/jamieconnelly/kerrini-users.git#master:app/db
    ports:
        - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  frontend:
    container_name: frontend
    build: https://github.com/jamieconnelly/kerrini-frontend.git
    healthcheck:
      test: exit 0

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    volumes_from:
      - frontend
    depends_on:
      users-service:
        condition: service_started
      frontend:
        condition: service_healthy
    links:
      - users-service

  users-service:
    container_name: users-service
    build: https://github.com/jamieconnelly/kerrini-users.git
    expose:
      - 5000
    environment:
      - APP_SETTINGS=app.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
    command: gunicorn -b 0.0.0.0:5000 manage:app
